name: S3createandupload
on: [workflow_dispatch]

jobs:
  awslogin:
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          
  createbucket:
    runs-on: self-hosted
    steps:
      - name: createbucket
        run: aws s3 mb s3://frontendui12072025

  uploadfileintobucket:
    runs-on: self-hosted
    steps:
      - name: uploadfileintobucket
        run: aws s3 cp index.html s3://frontendui12072025
      
  
